const rawDrugsList = [
    // Pain Relief & Fever (1-10)
    { name: "Dolo 650mg Tablet", type: "Pain/Fever", mrp: 30.90, disc: 15, rx: false },
    { name: "Calpol 500mg Tablet", type: "Pain/Fever", mrp: 15.50, disc: 10, rx: false },
    { name: "Crocin Advance Tablet", type: "Pain/Fever", mrp: 20.00, disc: 12, rx: false },
    { name: "Combiflam Tablet", type: "Pain Relief", mrp: 45.00, disc: 18, rx: false },
    { name: "Brufen 400mg Tablet", type: "Pain Relief", mrp: 22.50, disc: 10, rx: true },
    { name: "Zerodol-SP Tablet", type: "Pain Relief", mrp: 115.00, disc: 20, rx: true },
    { name: "Nise 100mg Tablet", type: "Pain Relief", mrp: 95.00, disc: 15, rx: true },
    { name: "Voveran SR 100mg Tablet", type: "Pain Relief", mrp: 130.00, disc: 18, rx: true },
    { name: "Meftal Spas Tablet", type: "Antispasmodic", mrp: 48.00, disc: 12, rx: true },
    { name: "Saridon Tablet", type: "Headache", mrp: 42.00, disc: 10, rx: false },
    // Antibiotics (11-20)
    { name: "Augmentin 625 Duo Tablet", type: "Antibiotic", mrp: 220.50, disc: 20, rx: true },
    { name: "Moxikind-CV 625 Tablet", type: "Antibiotic", mrp: 180.00, disc: 15, rx: true },
    { name: "Azithral 500mg Tablet", type: "Antibiotic", mrp: 132.00, disc: 18, rx: true },
    { name: "Azee 500mg Tablet", type: "Antibiotic", mrp: 125.00, disc: 15, rx: true },
    { name: "Ciplox 500mg Tablet", type: "Antibiotic", mrp: 45.00, disc: 10, rx: true },
    { name: "Taxim-O 200mg Tablet", type: "Antibiotic", mrp: 110.00, disc: 15, rx: true },
    { name: "Zifi 200mg Tablet", type: "Antibiotic", mrp: 108.00, disc: 15, rx: true },
    { name: "Levoflox 500mg Tablet", type: "Antibiotic", mrp: 95.00, disc: 18, rx: true },
    { name: "Oflox 200mg Tablet", type: "Antibiotic", mrp: 88.00, disc: 15, rx: true },
    { name: "Monocef-O 200mg Tablet", type: "Antibiotic", mrp: 145.00, disc: 20, rx: true },
    // Antidiabetics (21-30)
    { name: "Glycomet 500 SR Tablet", type: "Antidiabetic", mrp: 55.00, disc: 15, rx: true },
    { name: "Glycomet-GP 2 Tablet", type: "Antidiabetic", mrp: 165.00, disc: 20, rx: true },
    { name: "Janumet 50/500mg Tablet", type: "Antidiabetic", mrp: 350.00, disc: 15, rx: true },
    { name: "Galvus Met 50/500mg Tablet", type: "Antidiabetic", mrp: 290.00, disc: 18, rx: true },
    { name: "Amaryl 1mg Tablet", type: "Antidiabetic", mrp: 110.00, disc: 15, rx: true },
    { name: "Zoryl M2 Tablet", type: "Antidiabetic", mrp: 140.00, disc: 15, rx: true },
    { name: "Jalra-M 50/500mg Tablet", type: "Antidiabetic", mrp: 260.00, disc: 18, rx: true },
    { name: "Jardiance 10mg Tablet", type: "Antidiabetic", mrp: 550.00, disc: 10, rx: true },
    { name: "Forxiga 10mg Tablet", type: "Antidiabetic", mrp: 480.00, disc: 12, rx: true },
    { name: "Trajenta 5mg Tablet", type: "Antidiabetic", mrp: 420.00, disc: 10, rx: true },
    // Cardiovascular (31-40)
    { name: "Telma 40mg Tablet", type: "Cardiac", mrp: 125.00, disc: 15, rx: true },
    { name: "Telma H Tablet", type: "Cardiac", mrp: 165.00, disc: 18, rx: true },
    { name: "Amlokind 5mg Tablet", type: "Cardiac", mrp: 28.00, disc: 10, rx: true },
    { name: "Amlodac 5mg Tablet", type: "Cardiac", mrp: 40.00, disc: 12, rx: true },
    { name: "Olmezest 20mg Tablet", type: "Cardiac", mrp: 135.00, disc: 15, rx: true },
    { name: "Nebicard 5mg Tablet", type: "Cardiac", mrp: 115.00, disc: 15, rx: true },
    { name: "Ramipres 2.5mg Tablet", type: "Cardiac", mrp: 68.00, disc: 10, rx: true },
    { name: "Metolar XR 50mg Tablet", type: "Cardiac", mrp: 85.00, disc: 15, rx: true },
    { name: "Atorva 20mg Tablet", type: "Cardiac", mrp: 160.00, disc: 18, rx: true },
    { name: "Rosuvas 10mg Tablet", type: "Cardiac", mrp: 185.00, disc: 20, rx: true },
    // Gastrointestinal (41-50)
    { name: "Pan 40mg Tablet", type: "Gastro/Acidity", mrp: 155.00, disc: 18, rx: true },
    { name: "Pantocid 40mg Tablet", type: "Gastro/Acidity", mrp: 168.00, disc: 15, rx: true },
    { name: "Pantocid DSR Capsule", type: "Gastro/Acidity", mrp: 210.00, disc: 20, rx: true },
    { name: "Omez 20mg Capsule", type: "Gastro/Acidity", mrp: 58.00, disc: 15, rx: true },
    { name: "Omez DSR Capsule", type: "Gastro/Acidity", mrp: 145.00, disc: 18, rx: true },
    { name: "Razo 20mg Tablet", type: "Gastro/Acidity", mrp: 115.00, disc: 15, rx: true },
    { name: "Razo D Capsule", type: "Gastro/Acidity", mrp: 175.00, disc: 20, rx: true },
    { name: "Aciloc 150mg Tablet", type: "Gastro/Acidity", mrp: 40.00, disc: 10, rx: true },
    { name: "Zinetac 150mg Tablet", type: "Gastro/Acidity", mrp: 38.00, disc: 10, rx: true },
    { name: "Domstal 10mg Tablet", type: "Gastro/Acidity", mrp: 35.00, disc: 12, rx: true },
    // Respiratory (51-60)
    { name: "Asthalin Inhaler", type: "Respiratory", mrp: 165.00, disc: 10, rx: true },
    { name: "Foracort 200 Inhaler", type: "Respiratory", mrp: 385.00, disc: 15, rx: true },
    { name: "Seroflo 250 Inhaler", type: "Respiratory", mrp: 410.00, disc: 18, rx: true },
    { name: "Duolin Inhaler", type: "Respiratory", mrp: 320.00, disc: 15, rx: true },
    { name: "Montair LC Tablet", type: "Allergy/Cold", mrp: 185.00, disc: 20, rx: true },
    { name: "Allegra 120mg Tablet", type: "Allergy", mrp: 215.00, disc: 18, rx: false },
    { name: "Okacet Tablet", type: "Allergy", mrp: 22.00, disc: 10, rx: false },
    { name: "Cetzine Tablet", type: "Allergy", mrp: 45.00, disc: 15, rx: false },
    { name: "Xyzal 5mg Tablet", type: "Allergy", mrp: 115.00, disc: 18, rx: true },
    { name: "Cheston Cold Tablet", type: "Cold/Flu", mrp: 55.00, disc: 12, rx: true },
    // Dermatological & Anti-Fungal (61-70)
    { name: "Betnovate-N Cream", type: "Derma", mrp: 45.00, disc: 10, rx: true },
    { name: "Betnovate-C Cream", type: "Derma", mrp: 52.00, disc: 10, rx: true },
    { name: "Candid-B Cream", type: "Derma", mrp: 115.00, disc: 15, rx: true },
    { name: "Tenovate Cream", type: "Derma", mrp: 95.00, disc: 15, rx: true },
    { name: "Fucidin Cream", type: "Derma", mrp: 165.00, disc: 18, rx: true },
    { name: "T-Bact Ointment", type: "Derma", mrp: 145.00, disc: 15, rx: true },
    { name: "Soframycin Ointment", type: "Derma", mrp: 55.00, disc: 10, rx: true },
    { name: "Lulimac Cream", type: "Derma", mrp: 220.00, disc: 20, rx: true },
    { name: "Itracoe 100mg Capsule", type: "Anti-Fungal", mrp: 165.00, disc: 18, rx: true },
    { name: "Fluca 150mg Tablet", type: "Anti-Fungal", mrp: 18.00, disc: 10, rx: true },
    // Vitamins & Supplements (71-80)
    { name: "Shelcal 500 Tablet", type: "Vitamin", mrp: 115.00, disc: 15, rx: false },
    { name: "Neurobion Forte Tablet", type: "Vitamin", mrp: 38.00, disc: 10, rx: false },
    { name: "Zincovit Tablet", type: "Vitamin", mrp: 105.00, disc: 15, rx: false },
    { name: "Supradyn Daily Tablet", type: "Vitamin", mrp: 55.00, disc: 12, rx: false },
    { name: "Revital H Capsule", type: "Supplement", mrp: 310.00, disc: 20, rx: false },
    { name: "A to Z Gold Capsule", type: "Supplement", mrp: 185.00, disc: 18, rx: false },
    { name: "Folvite 5mg Tablet", type: "Vitamin", mrp: 75.00, disc: 15, rx: false },
    { name: "Orofer XT Tablet", type: "Iron Supplement", mrp: 165.00, disc: 18, rx: false },
    { name: "Dexorange Syrup", type: "Iron Supplement", mrp: 145.00, disc: 15, rx: false },
    { name: "Limcee 500mg Tablet", type: "Vitamin", mrp: 25.00, disc: 10, rx: false },
    // Neuro, Thyroid, & Topicals (81-90)
    { name: "Stemetil MD Tablet", type: "Neuro/Vertigo", mrp: 65.00, disc: 12, rx: true },
    { name: "Vertin 16mg Tablet", type: "Neuro/Vertigo", mrp: 185.00, disc: 18, rx: true },
    { name: "Drotin DS Tablet", type: "Antispasmodic", mrp: 135.00, disc: 15, rx: true },
    { name: "Thyronorm 50mcg Tablet", type: "Thyroid", mrp: 165.00, disc: 18, rx: true },
    { name: "Eltroxin 50mcg Tablet", type: "Thyroid", mrp: 140.00, disc: 15, rx: true },
    { name: "Ultracet Tablet", type: "Pain Relief", mrp: 220.00, disc: 20, rx: true },
    { name: "Volini Pain Relief Gel", type: "OTC Topicals", mrp: 110.00, disc: 10, rx: false },
    { name: "Moov Pain Relief Ointment", type: "OTC Topicals", mrp: 145.00, disc: 12, rx: false },
    { name: "Iodex Balm", type: "OTC Topicals", mrp: 55.00, disc: 10, rx: false },
    { name: "Relispray 50g", type: "OTC Topicals", mrp: 165.00, disc: 15, rx: false },
    // Digestion & Household OTC (91-100)
    { name: "Gelusil MPS Liquid", type: "Antacid", mrp: 125.00, disc: 12, rx: false },
    { name: "Digene Tablets", type: "Antacid", mrp: 22.00, disc: 10, rx: false },
    { name: "Eno Lemon Powder", type: "Antacid", mrp: 65.00, disc: 5, rx: false },
    { name: "Eno Orange Powder", type: "Antacid", mrp: 65.00, disc: 5, rx: false },
    { name: "Pudin Hara Pearls", type: "Digestion", mrp: 45.00, disc: 10, rx: false },
    { name: "Electral Powder 21.8g", type: "ORS", mrp: 21.00, disc: 5, rx: false },
    { name: "Honitus Cough Syrup", type: "Cough/Cold", mrp: 105.00, disc: 12, rx: false },
    { name: "Vicks Vaporub 50g", type: "Cough/Cold", mrp: 145.00, disc: 10, rx: false },
    { name: "Vicks Inhaler", type: "Cough/Cold", mrp: 55.00, disc: 5, rx: false },
    { name: "Candid Dusting Powder 100g", type: "OTC Topicals", mrp: 145.00, disc: 15, rx: false }
];

export const DRUGS = rawDrugsList.map((drug, index) => ({
    id: index + 1,
    ...drug,
    price: Number((drug.mrp - (drug.mrp * drug.disc / 100)).toFixed(2))
}));
